name: Update osu-stats gist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm install  

      - name: Update Gist
        run: npm start
        env:
          GIST_ID: 68c3458672047ec25e61a8af730181c3
          OSU_USERNAME: weikuu
          OSU_MODE: osu
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLEINT_SECRET: ${{ secrets.CLIENT_SECRET }}